# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 3.6
        dist: xenial
        env: TOX_ENV=py36
        sudo: true
      - python: 3.7
        dist: xenial
        env: TOX_ENV=py37
        sudo: true

install:
  - pip install tox
  - pip install -e .

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
