# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python
image: 'Ubuntu'
environment:
  matrix:
    - PYTHON: "Python36"
      TOX_ENV: "py36"
    - PYTHON: "Python37"
      TOX_ENV: "py37"

init:
  - "python -V"

install:
  - "easy_install -U pip"
  - "pip install tox"
  - "pip install -e ."
  - "pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "tox -e %TOX_ENV%"

after_test:
  - "python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
